env:
  GCP_PROJECT: "nl-sandbox-lla9"
  GCP_COMPUTE_REGION: "europe-west4"
  GCP_K8S_CLUSTER_NAME: "kube-private-cluster"
  IMAGE_REGISTRY: "eu.gcr.io/nl-obp-mgmt-services-lla9"
  APP_CONFIG_DIR: "src/main/resources"
  APP_HEALTCHECK_URL: "http://localhost:8087/actuator/health"
  APP_IMAGE_NAME: "nl-hello-world"
  DB_DEV_DATABASE: "postgres"
  DB_DEV_HOST: 1.2.3.4
  DB_DEV_PORT: 5432
  DB_DEV_SCHEMA: "dev-db"
  DB_MIGRATIONS_FOLDER: "src/main/resources/db/migration"
  DB_TEST_DATABASE: "postgres"
  DB_TEST_HOST: 1.2.3.4
  DB_TEST_PORT: 5432
  DB_TEST_SCHEMA: "test-dn"
  K8S_CONFIGMAP_BASE_DIR: "kube"
  K8S_CONFIGMAP_NAME: "nl-hello-world"
  K8S_CONFIGMAP_FILE_NAME: "configMap.yaml"
  K8S_CONTAINER_NAME: "nl-hello-world"
  K8S_DEPLOYMENT_FILE: "kube/k8s-resources.yaml"
  K8S_DEPLOYMENT_NAME: "nl-hello-world-v1"
  K8S_DEV_NAMESPACE: "nl-dev"
  K8S_TEST_NAMESPACE: "nl-test"
steps:
  - label: ":male-scientist: Quality Checks"
    command: "scripts/quality-check.sh"
    timeout_in_minutes: 10
    branches: master release/*
    agents:
      queue: 'obp-nl'
  - wait
  - label: ":package: Build and create container image :whale:"
    command: "scripts/build.sh"
    artifact_paths: "build/libs/*.jar"
    timeout_in_minutes: 10
    branches: master release/*
    agents:
      queue: 'obp-nl'
  - wait
  - label: ":rocket: Deploy to Dev"
    command: "scripts/deploy.sh dev"
    timeout_in_minutes: 10
    branches: master release/*
    agents:
      queue: 'obp-nl'
  # - wait
  # - block: "Release"
  #   prompt: "Release to next environment?"
  # - label: ":package: Create release"
  #   command: "scripts/release.sh"
  #   timeout_in_minutes: 10
  #   branches: master release/*
  #   agents:
  #     queue: 'obp-nl'
  # - wait
  # - label: ":rocket: Deploy to Test environment"
  #   command: "scripts/deploy.sh test"
  #   timeout_in_minutes: 10
  #   branches: master release/*
  #   agents:
  #     queue: 'obp-nl'
